# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ood_detection',
                'doc_host': 'https://yashwiai.github.io',
                'git_url': 'https://github.com/yashwiai/ood_detection',
                'lib_path': 'ood_detection'},
  'syms': {'ood_detection.core': {'ood_detection.core.foo': ('core.html#foo', 'ood_detection/core.py')}}}