# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ood_detection',
                'doc_host': 'https://yashwiai.github.io',
                'git_url': 'https://github.com/yashwiai/ood_detection',
                'lib_path': 'ood_detection'},
  'syms': { 'ood_detection.core': { 'ood_detection.core.OODMetric': ('core.html#oodmetric', 'ood_detection/core.py'),
                                    'ood_detection.core.OODMetric.__init__': ('core.html#oodmetric.__init__', 'ood_detection/core.py'),
                                    'ood_detection.core.OODMetric.compute_rmd': ( 'core.html#oodmetric.compute_rmd',
                                                                                  'ood_detection/core.py'),
                                    'ood_detection.core.compute_mahalanobis_distance': ( 'core.html#compute_mahalanobis_distance',
                                                                                         'ood_detection/core.py'),
                                    'ood_detection.core.compute_mean_and_covariance': ( 'core.html#compute_mean_and_covariance',
                                                                                        'ood_detection/core.py')}}}